In [1]:
2+3

5

In [2]:
import numpy as np

In [9]:
nums =[[[1,2,3],[4,2,6]],[[1,2,3],[4,2,6]]] 
# no. of brackets shows dimension. Like here there are 3 brackets so this is 3-d matrix.

In [10]:
nums=np.array(nums)

In [11]:
nums

array([[[1, 2, 3],
        [4, 2, 6]],

       [[1, 2, 3],
        [4, 2, 6]]])

In [13]:
#For dimension - 2d,3d etc
nums.ndim

3

In [15]:
#For dimensions - no.of rows aand columns
nums.shape

(2, 2, 3)

In [16]:
## You can only store a single data type in numpy array that is the reason it is fast. 
# while in list(Python) you can add all the types of data types

In [18]:
# to check data type
nums.dtype

dtype('int32')

# # Create array using numpy functions

In [19]:
#zeros,#ones,#eye , #diag, randint,rand,randn

In [21]:
arr= np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [23]:
# if we pass Tuple
arra =np.zeros((2,3))
arra

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arra =np.ones((2,3))
arra

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
arra =np.ones(4)
arra

array([1., 1., 1., 1.])

In [30]:
# Diagonal values will be one rest will be zeros. 
arra =np.eye(4)
arra

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#for 3 rows and 4 columns you will get 1's diagonally for 3 rows
arra =np.eye(3,4)
arra

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
#diagonally you will get the mentioned values you have given in a square matrix
arra =np.diag([1,2,3,4])
arra

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
np.diag(arra)

array([1, 2, 3, 4])

In [35]:
# we will get 4 random integer between 1 and 15
rand_arra = np.random.randint(1,15,4)
rand_arra

array([ 9, 14,  6, 11])

In [36]:
# Any digits between 0 and 1
rand_arra = np.random.rand(4)
rand_arra

array([0.85023901, 0.98563667, 0.99922337, 0.64963973])

In [37]:
#2-d array
rand_arra = np.random.rand(2,3)
rand_arra

array([[0.12951639, 0.56765095, 0.53233089],
       [0.81894243, 0.7613568 , 0.3065357 ]])

In [38]:
# you will get negative and positive numbers and the midd point will be zero
rand_arra = np.random.randn(4)
rand_arra

array([ 0.78991369,  0.62829172, -0.19910572, -1.88831357])

In [40]:
# If you want mean of these numbers
rand_arra = np.random.randn(15)
np.mean(rand_arra)

-0.037790273768482936

In [41]:
rand_arra = np.random.randn(15000) # zero ke pass hoga mean badi value ke liye
np.mean(rand_arra)

0.007968853845390915

# Reshaping of data

In [42]:
import numpy as np

In [43]:
arr = np.random.randint(1,100,20)
arr

array([85, 68, 84, 15,  2, 34, 44, 32, 56, 54, 51, 56,  2, 82, 70, 16, 27,
        6, 91,  7])

In [45]:
arr = np.random.randint(1,100,20)
arr = arr.reshape(2,10) 
# the multiplication of the digits we are passing should be equivalent to 20 otherwise it will give an error
arr

array([[94,  9, 21, 86, 48, 74, 41, 19, 64, 51],
       [22, 24, 49, 36,  9,  4, 15, 94, 55, 62]])

In [46]:
arr.shape

(2, 10)

In [47]:
arr.ndim

2

In [48]:
# for reshaping to 3d array

arr = np.random.randint(1,100,50)
arr = arr.reshape(2,5,5) # multiplication equals to 50
arr

array([[[98, 64, 33, 84, 83],
        [99,  6, 38, 71, 90],
        [71, 53, 29, 51, 16],
        [35,  9, 95,  7, 63],
        [65, 85, 36, 11, 23]],

       [[93, 92, 24, 20, 16],
        [80, 71, 86, 51,  1],
        [19, 30, 73, 98, 77],
        [32, 45, 55, 90, 23],
        [93, 69, 55, 98, 98]]])

In [49]:
arr.shape

(2, 5, 5)

In [50]:
arr.ndim

3

# -1 usage in reshaping the array

In [56]:
import numpy as np

In [58]:
arr = np.arange(1,11)

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
# if we use -1 instead of 5 numpy will consider it 5 by itself and will give same o/p as above 
# because the multiplication should be same(Here it is 10)
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr = np.arange(1,111)

In [64]:
arr.size

110

In [65]:
arr.reshape(5,-1)
# it will calculate columns by itself

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [66]:
arr.reshape(-1,5)
# it will calculate rows by itself

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

# Create same random numbers

In [67]:
import numpy as np

In [75]:
#If you want that all of us have same random numbers then use "np.random.seed(123)" before randint function

np.random.seed(123)
arr = np.random.randint(1,101,10)
arr

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [76]:
arr.size

10

In [77]:
# If we reshape this in 2d array

np.random.seed(12)
arr = np.random.randint(1,101,15).reshape(3,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [74]:
arr.size

15

# Indexing and slicing 1d array

In [78]:
import numpy as np

In [79]:
arr = np.array([5,10,15,20,25])

In [80]:
arr

array([ 5, 10, 15, 20, 25])

In [81]:
arr[0]

5

In [82]:
arr[1]

10

In [83]:
# Negative indexing
arr[-1]

25

In [84]:
arr[-4]

10

In [85]:
# Slicing

arr[0:3]  # It will go till 3rd index but it will not include the 3rd indexed element here

array([ 5, 10, 15])

In [86]:
arr[1:]

array([10, 15, 20, 25])

In [87]:
arr[:2]

array([ 5, 10])

In [88]:
arr[-3:]

array([15, 20, 25])

In [90]:
# Sequence step argument

arr[0:5:2]

array([ 5, 15, 25])

In [91]:
# For reversing your array

arr[::-1]

array([25, 20, 15, 10,  5])

# Create 2d array

In [92]:
import numpy as np

In [93]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [94]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Indexing using double bracket notation

In [95]:
matrix[0][1]

10

In [96]:
matrix[1][1]

25

# Indexing using single bracket notation (Recommended)

In [98]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [99]:
matrix[0,1]

10

In [100]:
matrix[2,2]

45

# Slicing using single bracket notation

In [101]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [102]:
# we need to extract a small array from this array
#5,10
#20,25

matrix[:2,:2]
# from 0th row se start karte huye jana hai 2nd row; isliye (:2)
# from 0th column se start karte huye jana hai 2nd column; isliye (:2)
# Aur 2nd indexed digit will be skipped

array([[ 5, 10],
       [20, 25]])

In [108]:
# 25,30
# 40,45

matrix[1:,1:] # From 1st row and 1st column

array([[25, 30],
       [40, 45]])

In [110]:
# Bigger array

np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [111]:
# 87, 98, 97
# 33, 47, 97
# 79, 37, 97

matrix2 [1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [113]:
matrix2 [2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# View VS Copy

In [114]:
import numpy as np

In [115]:
arr = np.array([5,10,15,20,25,30])

In [116]:
#View me sliced_array is part of arr
sliced_array = arr[2:5]
sliced_array

array([15, 20, 25])

In [117]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [118]:
sliced_array

array([15, 20, 25])

In [119]:
arr[2:5] = 0
sliced_array

array([0, 0, 0])

In [120]:
arr # values changes in arr also if we are changing the values for sliced_array
# that is why we see the view of sliced_array in arr

array([ 5, 10,  0,  0,  0, 30])

In [122]:
#COPY

arr = np.array([5,10,15,20,25,30])
sliced_array = arr[2:5].copy()
sliced_array

array([15, 20, 25])

# Conditional selection

In [123]:
import numpy as np

In [125]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
mask = arr>5

In [127]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [128]:
arr[arr<4]

array([1, 2, 3])

In [129]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [130]:
arr[arr==5]

array([5])

In [131]:
arr[arr%2==0] = 0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# Operation on array with scaler

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr * 2

array([2, 4, 6, 8])

In [5]:
arr + 5

array([6, 7, 8, 9])

In [6]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [7]:
arr**3

array([ 1,  8, 27, 64], dtype=int32)

In [8]:
arr**4

array([  1,  16,  81, 256], dtype=int32)

In [9]:
arr = np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [10]:
arr/1

array([[1., 2.],
       [3., 4.]])

In [12]:
1/0 # this is an error in python unlike numpy

ZeroDivisionError: division by zero

In [13]:
arr/0 # this will give you warning and output in numpy not error

E:\Users\Miss Sharma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

# Numerical operations on arrays(Two or more)

In [14]:
import numpy as np

In [15]:
arr1= np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [16]:
arr1+arr2

array([ 6,  8, 10, 12])

In [17]:
arr1*arr2

array([ 5, 12, 21, 32])

In [18]:
arr1**arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [19]:
arr1*arr1

array([ 1,  4,  9, 16])

In [20]:
arr1= np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 =np.array([9,10,11,12])

In [21]:
arr1/arr1*arr3

array([ 9., 10., 11., 12.])

In [22]:
np.random.seed(123)

In [24]:
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)

In [26]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [27]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [28]:
matrix1+matrix2 # shape of the matrix should be same

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [29]:
matrix1 * matrix2 #this matrix multiplication is different from linear algebra so the result will vary

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [30]:
matrix1.dot(matrix2) # for result as linear algebra matrix multiplication

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

# Some more useful numpy concept

In [31]:
import numpy as np

In [32]:
arr = np.array([2,80,1,97,5])

In [33]:
np.min(arr) # for minimum number in array

1

In [35]:
np.max(arr) #for maximum no.

97

In [36]:
# position of the min. number
np.argmin(arr)

2

In [37]:
# position of the max. number
np.argmax(arr)

3

In [38]:
#for square root
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [39]:
np.exp(arr) # for exponent

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [40]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [41]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [42]:
# if we want 50 evenly spaced numbers between 1 to 15
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [43]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [45]:
# how to make your array a boolean array
arr2 = np.array([1,2,3,0],dtype='bool')
arr2

array([ True,  True,  True, False])

In [46]:
# can also be done(Iteration)
for i in arr2:
    print(i)

True
True
True
False


# Numpy Axis

In [47]:
import numpy as np

In [48]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [49]:
np.sum(matrix)  # Sum of all the elements

39

In [50]:
# np.sum(matrix) - can also be written as

matrix.sum()

39

In [54]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [51]:
# rows =1 , columns = 0
# how to find minimum values row wise
np.min(matrix, axis = 1)

array([3, 2, 1])

In [52]:
# how to find max values column wise
np.max(matrix, axis = 0)

array([ 7,  4, 10])

In [53]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [55]:
np.cumsum(matrix) # Cummulative Sum

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [56]:
# Cummulative Sum - row wise
np.cumsum(matrix, axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [57]:
# Cummulative Sum - column wise
np.cumsum(matrix, axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [58]:
np.prod(matrix,axis=1) # product row wise Eg.- (3*3*7)

array([63, 80, 14])

# Shuffle and Unique

In [59]:
import numpy as np
np.random.seed(123)
arr = np.random.randint(1,15,15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [61]:
np.random.shuffle(arr) # Elements will get shuffled
arr

array([14, 10,  3, 11,  7,  2,  2,  3, 13, 12,  2,  7,  4, 10,  1])

In [62]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [63]:
np.unique(arr).size

10

In [64]:
np.unique(arr, return_index= True, return_counts= True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([14,  5,  2, 12,  4,  1,  3,  9,  8,  0], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

# Horizontal and Vertical stacking

In [66]:
np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [67]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [68]:
# To concatenate 2 matrix horizontally
# hstack main hum tuple pass karenge

np.hstack((matrix1,matrix2))


array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [69]:
# To concatenate 2 matrix vertically
# vstack main hum tuple pass karenge

np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [71]:
#1d  array hstack [ 1,2,3,4,5,6]

arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

In [72]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [73]:
np.vstack((arr1,arr2)) # this will change in 2d array

array([[1, 2, 3],
       [4, 5, 6]])